[package]
name = "rs-git-fsmonitor"
version = "0.1.0"
authors = ["Jason Gavris <jgavris@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
